language: node_js
node_js:
  - "6"
cache:
  directories:
  - node_modules
before_install:
  - npm i -g npm@latest
install:
  - npm install
notifications:
    slack: cloudbyte-team:oxEB3rpO5tKqmRWhIuDxUUy4
